name: Bug report
description: Report an issue or defect for Monsta Tools or Submission
title: "[Bug] <brief description>"
labels: [bug]
body:
  - type: input
    id: reporter_name
    attributes:
      label: Your Name
      description: Please enter your full name.
      placeholder: e.g. Jane Doe
    validations:
      required: true

  - type: dropdown
    id: employment_type
    attributes:
      label: Are you outsource or in-house?
      options:
        - In-house
        - Outsource
    validations:
      required: true

  - type: input
    id: pc_number
    attributes:
      label: PC Number (optional)
      description: If reporting from a specific PC, provide its number.
      placeholder: e.g. MON-###
    validations:
      required: false

  - type: dropdown
    id: department
    attributes:
      label: Department
      options:
        - LAYOUT
        - ASSET
        - ANIMATION
        - RENDERING / LIGHTING
        - FX
        - COMPOSITING
    validations:
      required: true

  - type: dropdown
    id: tool
    attributes:
      label: Which Monsta product/tool is this about?
      options:
        - Monsta Tools
        - Monsta Submission
    validations:
      required: true

  - type: input
    id: subtool
    attributes:
      label: Sub-tool (optional)
      description: Specify the sub-tool, script, or module if relevant
      placeholder: e.g. Assets Publisher, Shot Checker
    validations:
      required: false

  - type: input
    id: short-summary
    attributes:
      label: Short summary
      placeholder: e.g. Ingest panel throws error on upload
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: What happened?
      description: Please describe the bug in detail. You can drag & drop images.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the bug.
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Info (optional)
      placeholder: email@example.com
    validations:
      required: false
