name: Bug report
description: Report a bug to help us improve Monsta Tools and Submissions.
title: "[Bug] "
labels: [bug]
body:
  - type: dropdown
    id: department
    attributes:
      label: Department
      description: Choose the department most related to this issue.
      options:
        - LAYOUT
        - ASSET
        - ANIMATION
        - RENDERING / LIGHTING
        - FX
        - COMPOSITING
    validations:
      required: true

  - type: dropdown
    id: tool
    attributes:
      label: Which Monsta product/tool is this about?
      description: Select the main tool related to this issue.
      options:
        - Monsta Tools
        - Monsta Submission
    validations:
      required: true

  - type: input
    id: subtool
    attributes:
      label: Sub-tool (optional)
      description: Specify the sub-tool or module if relevant (e.g. publish, ingest, etc.)
      placeholder: (e.g., Assets Publisher, Shot Checker)
    validations:
      required: false

  - type: input
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug you encountered.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please provide step-by-step instructions to reproduce the bug. You can drag and drop images here for screenshots.
      placeholder: 1. Go to '...'
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Info (optional)
      placeholder: email@example.com
