name: Bug report
description: Create a report to help us improve Monsta Tools or Submission. Please fill in all details as clearly as possible.
title: "[Bug] <brief description>"
labels: [bug]
body:
  - type: textarea
    id: context
    attributes:
      label: Reporter Info & Context
      placeholder: |
        Name: 
        In-house or Outsource: 
        PC Number (if any): 
        Department: 
        Tool: 
        Sub-tool: 
        Contact info: 
    validations:
      required: true

  - type: input
    id: short-summary
    attributes:
      label: Short summary
      description: Briefly summarize your bug (this will appear in the title)
      placeholder: e.g. Ingest panel throws error on upload
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: What happened?
      description: Please describe the bug in detail. You can drag & drop screenshots or images here.
      placeholder: Please describe the bug in detail.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce this issue, including any details to help us identify the problem.
      placeholder: 1. Go to '...'
    validations:
      required: false
