name: Feature request
about: Suggest an idea for this project
title: "[Feature] "
labels: enhancement
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: A clear and concise description of what the problem is.
      placeholder: e.g., I'm always frustrated when [...]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Describe the solution you'd like**
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: A clear and concise description of what you want to happen.
      placeholder: I would like [...]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Describe alternatives you've considered**
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I have considered [...]
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Additional context**
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add any other context or screenshots here
    validations:
      required: false
