name: Feature request
description: Suggest a new feature for Monsta Tools or Submission
title: "[Feature] <brief description>"
labels: [feature]
body:
  - type: input
    id: reporter_name
    attributes:
      label: Your Name
      description: Please enter your full name.
      placeholder: e.g. Jane Doe
    validations:
      required: true

  - type: dropdown
    id: employment_type
    attributes:
      label: Are you outsource or in-house?
      options:
        - In-house
        - Outsource
    validations:
      required: true

  - type: input
    id: pc_number
    attributes:
      label: PC Number (optional)
      description: If relevant, provide your PC number.
      placeholder: e.g. PC-042
    validations:
      required: false

  - type: dropdown
    id: department
    attributes:
      label: Department
      options:
        - LAYOUT
        - ASSET
        - ANIMATION
        - RENDERING / LIGHTING
        - FX
        - COMPOSITING
    validations:
      required: true

  - type: dropdown
    id: tool
    attributes:
      label: Which Monsta product/tool is this about?
      options:
        - Monsta Tools
        - Monsta Submission
    validations:
      required: true

  - type: input
    id: subtool
    attributes:
      label: Sub-tool (optional)
      description: Specify the sub-tool, script, or module if relevant
      placeholder: e.g. Assets Publisher, Shot Checker
    validations:
      required: false

  - type: input
    id: short-summary
    attributes:
      label: Short summary
      placeholder: e.g. Add batch publish feature to Submission UI
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: What problem or need does this feature address?
      description: Briefly explain why this would be useful.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Describe the solution you'd like
      description: Include anything that would help us understand your idea. You can drag & drop images.
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Info (optional)
      placeholder: email@example.com
    validations:
      required: false
